apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: argocd.localhost
  dnsNames:
  - argocd.localhost
