apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-cert
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: grafana-issuer
    kind: Issuer
  commonName: grafana.localhost
  dnsNames:
  - grafana.localhost
