apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  project: default

  source:
    path: manifests/cluster-install
    repoURL: https://github.com/argoproj/argo-rollouts
    targetRevision: v0.10.2

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
