apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default

  source:
    path: argocd/overlays/production
    repoURL: https://github.com/BadLiveware/gitops-kustomize.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true