apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-resources
spec:
  project: default

  source:
    path: prometheus-operator-resources
    repoURL: https://github.com/BadLiveware/gitops-kustomize.git
    targetRevision: HEAD

  destination:
    namespace: prometheus-operator
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
