---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default

  source:
    # path: argocd/overlays/production
    # repoURL: https://github.com/BadLiveware/gitops-kustomize.git
    # targetRevision: HEAD
    chart: kube-prometheus-stack
    targetRevision: 13.13.0
    repoURL: https://prometheus-community.github.io/helm-charts

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true