apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  project: default

  source:
    path: root/base
    repoURL: https://github.com/BadLiveware/gitops-kustomize.git
    targetRevision: HEAD

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc