apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- argo-cd-server-service.yaml

configMapGenerator:
- name: argocd-cm
  behavior: merge
  literals:
  - admin.enabled='true'
  - statusbadge.enabled='true'
  - users.anonymous.enabled='true'
  - ga.trackingid='UA-105170809-6'

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

patchesJson6902:
- path: ./argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

